language: java

env:
  - DISPLAY=:99.0

before_install:
  - sudo apt-get install metacity

before_script:
  - wget https://downloads.sourceforge.net/project/xmltask/xmltask/1.16.1/xmltask.jar 
  - export CLASSPATH=`pwd`/xmltask.jar:$CLASSPATH
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16  +extension RAND"
  - sleep 5 # give xvfb some time to start
  - metacity --sm-disable --replace &

script: 
  - ant buildAMO
  - cd test
  - perl executeTests.pl --version 59.0a1